= code optimisation group meeting minutes 10th feb 2021

A general note to put your stuff on to advertise services / products: https://riscv.org/exchange/

. *Tariq*: Send charter again to help@riscv.org (*done*)

= Code size reduction ISA review

. *Tariq*:Redo the example with GCC10 from the top of the readme, and the code it is generated from (*done*)

Note that we can use Godbolt.org for different compilers to see the compiled output in real time

. *Tariq*: Need to save/restore table jump base on a context switch (*done*)

. *Tariq*: Proof of concept – for push/pop and others, quantify logic cost and publish that

. *Tariq*: Talk to platform team about TBLJAL who are engaged with the profiles team – Kumar new chair / Atish (*done*)

. *Tariq*: Note that we could do push/pop in the linker so don’t have to have to recompile libraries (*done*)

. Multi-move – should be used by the compiler which will target the registers, maybe peephole in the linker, relies on relocations generated by the compiler

. *Tariq*: Mail help@riscv.org about jfrog (*done*)

. *Tariq*: look at Zero page functionality from David Horner – SiFive reserves lowest bit of zero page as guaranteed traps and also for debug

. *Tariq*: don't forget Sign extend byte/half-word

. *Tariq*: Tell Wei Wu about open source benchmarks and he’ll add into continuous integration

Next meeting
26th Feb 7am, topic is compiler optimisation
