= RISC-V 48-bit code-size reduction extension proposal
Version 0.1
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 4
:numbered:
:xrefstyle: short
:le: &#8804;
:rarr: &#8658;

This document describes 48-bit instructions proposed to help reduce code-size.

== Rationale

The RISC-V architecture allows 48-bit, and longer encodings to be specified.
The idea behind this 48-bit proposal is to allow much larger immediate values
than are permitted by the standard encodings.

These instructions are experimental, and whether they are used in the final
version of the code-size reduction ISA extension mainly depends on 

* whether the compiler/linker can make good use of them, and so they show a worthwhile benefit
* whether people are happy to implement 48-bit instructions in general

They will only be included if they can show a sufficient benefit over 32/16-bit encodings, but note that
they allow more encoding space to be allocated than is otherwise possible.

Load-32-bit-immediate (`L.LI`) showed high benefit in the absence of the other proposed instructions - it's possible that with
the other instructions implemented `L.LI` is not required. TBD.

Also the length of the immediate values needs to be balanced against the available encoding space. Shorter immediates means that more opcodes can be encoded, but of course may reduce the usefulness of the longer encoding. 
It's important that bits [47:32] only contain immediate data - not encoding information, so that the instruction
decoder still operates on bits [31:0] only. This simplifies the microarchitecture, but is unlikely to scale to 64-bit and longer encodings.

=== Opcode Assignment

[#LLI_encoding]
.proposed L.LI encoding
[width="100%",options=header]
|=======================================================================
|47:32|31:16|15:12|11:7    |6:0    |instruction
2+|imm[31:0]                |  0000  |rd      |0011111| L.LI
|=======================================================================

[#other_encodings]
.proposed encodings for other instructions
[width="100%",options=header]
|=======================================================================
|47:32|31:30|29:25     |24:20 |19:15|14:12|11:7    |6:0    |instruction
|imm[25:10]     |00  2+|imm[9:0]      |rs1     |001  |rd      |0011111| L.ADDI
|imm[25:10]     |01  2+|imm[9:0]      |rs1     |001  |rd      |0011111| L.ANDI
|imm[25:10]     |10  2+|imm[9:0]      |rs1     |001  |rd      |0011111| L.JAL
  
9+|Load/store with longer immediate offset

|imm[25:10]     |00  2+|imm[9:0]      |rs1     |000  |rd      |1011111| L.LBU
|imm[25:10]     |01  2+|imm[9:0]      |rs1     |000  |rd      |1011111| L.LHU
|imm[25:10]     |10  2+|imm[9:0]      |rs1     |000  |rd      |1011111| L.LW
|imm[25:10]     |11  2+|imm[9:0]      |rs1     |000  |rd      |1011111| L.LD (RV64+)

|imm[25:10]     |00    |imm[9:5]   |rs2 |rs1   |001  |imm[4:0]|1011111| L.SB
|imm[25:10]     |01    |imm[9:5]   |rs2 |rs1   |001  |imm[4:0]|1011111| L.SH
|imm[25:10]     |10    |imm[9:5]   |rs2 |rs1   |001  |imm[4:0]|1011111| L.SW
|imm[25:10]     |11    |imm[9:5]   |rs2 |rs1   |001  |imm[4:0]|1011111| L.SD (RV64+)

9+|Preindexed Load/store, and update address register

|imm[25:10]     |00  2+|imm[9:0]      |rs1     |010  |rd      |1011111| L.LBU.U
|imm[25:10]     |01  2+|imm[9:0]      |rs1     |010  |rd      |1011111| L.LHU.U
|imm[25:10]     |10  2+|imm[9:0]      |rs1     |010  |rd      |1011111| L.LW.U
|imm[25:10]     |11  2+|imm[9:0]      |rs1     |010  |rd      |1011111| L.LD.U (RV64+)

|imm[25:10]     |00    |imm[9:5]   |rs2 |rs1   |011  |imm[4:0]|1011111| L.SB.U
|imm[25:10]     |01    |imm[9:5]   |rs2 |rs1   |011  |imm[4:0]|1011111| L.SH.U
|imm[25:10]     |10    |imm[9:5]   |rs2 |rs1   |011  |imm[4:0]|1011111| L.SW.U
|imm[25:10]     |11    |imm[9:5]   |rs2 |rs1   |011  |imm[4:0]|1011111| L.SD.U (RV64+)
|=======================================================================

[#semantics]
.semantics
[width="100%",options=header]
|=======================================================================
|instruction | definition
| L.LI       | rd = sign_ext(imm)
| L.ADDI     | rd = rs1 + sign_ext(imm)
| L.ANDI     | rd = rs1 & sign_ext(imm)
| L.JAL      | jump to PC+sign_ext(imm), link to ra
| L.LBU      | rd = zero_ext((Memory[rs1 + sign_ext(imm)])[7:0])
| L.LHU      | rd = zero_ext((Memory[rs1 + sign_ext(imm)])[15:0])
| L.LW       | rd = sign_ext((Memory[rs1 + sign_ext(imm)])[31:0])
| L.LD       | rd = sign_ext((Memory[rs1 + sign_ext(imm)])[63:0])
| L.SB       | Memory[rs1 + sign_ext(imm)][7:0]  = rs2
| L.SH       | Memory[rs1 + sign_ext(imm)][15:0] = rs2
| L.SW       | Memory[rs1 + sign_ext(imm)][31:0] = rs2
| L.SD       | Memory[rs1 + sign_ext(imm)][63:0] = rs2
| L.LBU.U    | rd = zero_ext((Memory[rs1 + sign_ext(imm)])[7:0]);  rs1+=sign_ext(imm);
| L.LHU.U    | rd = zero_ext((Memory[rs1 + sign_ext(imm)])[15:0]); rs1+=sign_ext(imm);
| L.LW.U     | rd = sign_ext((Memory[rs1 + sign_ext(imm)])[31:0]); rs1+=sign_ext(imm);
| L.LD.U     | rd = sign_ext((Memory[rs1 + sign_ext(imm)])[63:0]); rs1+=sign_ext(imm);
| L.SB.U     | Memory[rs1 + sign_ext(imm)][7:0]  = rs2; rs1+=sign_ext(imm);
| L.SH.U     | Memory[rs1 + sign_ext(imm)][15:0] = rs2; rs1+=sign_ext(imm);
| L.SW.U     | Memory[rs1 + sign_ext(imm)][31:0] = rs2; rs1+=sign_ext(imm);
| L.SD.U     | Memory[rs1 + sign_ext(imm)][63:0] = rs2; rs1+=sign_ext(imm);
|=======================================================================

* should there also be load/store quad?

==== Assembly Examples

[source,sourceCode,text]
----
l.li        a5,0xf00100;     # a5 = 0xf00100
     
l.addi      a5,a6,0xf00100;  # a5 = a6 + 0xf00100
l.andi      a5,a6,0xf00100;  # a5 = a6 & 0xf00100
     
l.lbu       a5,0xf00100(a6); # load bottom byte of a5 from address a6+0xf00100, zero extend
l.lhu       a5,0xf00100(a6); # load bottom half of a5 from address a6+0xf00100, zero extend
l.lw        a5,0xf00100(a6); # load bottom word from a5 from address a6+0xf00100, sign extend for RV64+
l.ld        a5,0xf00100(a6); # load double word from a5 from address a6+0xf00100, RV64+ only, sign extend for RV128
     
l.sbu       a5,0xf00100(a6); # store bottom byte of a5 to address a6+0xf00100
l.shu       a5,0xf00100(a6); # store bottom half of a5 to address a6+0xf00100
l.sw        a5,0xf00100(a6); # store bottom word of a5 to address a6+0xf00100
l.sd        a5,0xf00100(a6); # store bottom double word of a5 to address a6+0xf00100, RV64+ only

l.lbu.u     a5,0xf00100(a6); # load bottom byte of a5 from address 0xf00100, zero extend. Set a6 = 0xf00100
l.lhu.u     a5,0xf00100(a6); # load bottom half of a5 from address 0xf00100, zero extend. Set a6 = 0xf00100
l.lw.u      a5,0xf00100(a6); # load bottom word from a5 from address 0xf00100, sign extend for RV64+. Set a6 = 0xf00100
l.ld.u      a5,0xf00100(a6); # load double word from a5 from address 0xf00100, RV64+ only, sign extend for RV128. Set a6 = 0xf00100

l.sbu.u     a5,0xf00100(a6); # store bottom byte of a5 to address 0xf00100. Set a6 = 0xf00100
l.shu.u     a5,0xf00100(a6); # store bottom half of a5 to address 0xf00100. Set a6 = 0xf00100
l.sw.u      a5,0xf00100(a6); # store bottom word of a5 to address 0xf00100. Set a6 = 0xf00100
l.sd.u      a5,0xf00100(a6); # store bottom double word of a5 to address 0xf00100, RV64+ only. Set a6 = 0xf00100
