= Move a pair of registers to another pair

`mv` instructions are the most common in both the benchmark suite and the https://wiki.debian.org/RISC-V[RISC-V Debian distro].

This proposal includes several proposals to choose from.

Common uses for `mv` instructions are:

- moving function arguments into saved registers at the end of a function prologue, to save the arguments before calling another function. 
  This case is covered by the https://github.com/riscv/riscv-code-size-reduction/blob/master/ISA%20proposals/Huawei/riscv_push_pop_extension_RV32_RV64_UABI.adoc[PUSH/POP proposal] for `a0-a2`:

[source,sourceCode,text]
----
# from FPMark
00010402 <helper_atan1M>: 
   10402:	8198                	push	{ra,s0-s7},-64
   10404:	89aa                	mv	s3,a0 ;# use push {ra,s0-s7},{a0-a2},-64
   10406:	892e                	mv	s2,a1 ;# use push {ra,s0-s7},{a0-a2},-64
   10408:	84b2                	mv	s1,a2 ;# use push {ra,s0-s7},{a0-a2},-64
   1040a:	8bb6                	mv	s7,a3 ;#others aren't optimised by ISA extensions
   1040c:	8abe                	mv	s5,a5
   1040e:	8a42                	mv	s4,a6
   10410:	8b46                	mv	s6,a7
----

- assembling functions arguments for function calls, and for occasionally for return values if `a1` is also required. These cases are covered by this proposal.

[source,sourceCode,text]
----
# from the same FPMark function, this case can be optimised by this proposal
   10444:	85a6                	mv	a1,s1 ;#use mv (a0, a1), (s0, s1)
   10446:	8522                	mv	a0,s0 ;#use mv (a0, a1), (s0, s1)
   10448:	0eb000ef          	jal	ra,10d32 <th_strncpy>
   ....
#only a0 as a return value, can be merged with popret (32-bit encoding only)
   10480:	8522                	mv	a0,s0 ;#use popret {ra,s0-s7},{s0},64
   10482:	8194                	popret	{ra,s0-s7},64
----

These different proposals all use a single 16-bit encoding to do the work of two 16-bit register moves.

== prorposal: S to A moves

[#proposed-16bit-encodings_stoa]
.proposed 16-bit encodings for S to A moves
[width="100%",options=header]
|===================================================================================================
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6  | 5  | 4 | 3 | 2 | 1 | 0 |instruction  | code points       
5+| ?????         3+| sreg1[2:0]      3+| sreg2[2:0]         5+| ????? | C.MVA01S07 | 1<<6
5+| ?????         3+| sreg1[2:0]      3+| sreg2[2:0]         5+| ????? | C.MVA23S07 | 1<<6
18+|for these forms sreg1[2]=0, sreg2[2]=0
5+| ????? | ?     2+| sreg1[1:0] | ?  2+| sreg2[1:0]         5+| ????? | C.MVA01S03 | 1<<4
5+| ????? | ?     2+| sreg1[1:0] | ?  2+| sreg2[1:0]         5+| ????? | C.MVA23S03 | 1<<4
|===================================================================================================

`sreg[12]` specify which two `s` registers are moved, using the ABI name only so that `s0-s7` or `s0-s3` can be moved into the `(a0,a1)` and `(a2,a3)` register pairs.

the choice betwen the `S03` and `S07` versions is the trade-off between encoding space and code-size reduction benefit.

[source,sourceCode,text]
----
# c.mva01s: sreg1 = 0; sreg2 = 0;
mv (a0, a1), (s0, s0) ; # mv a0, s0; mv a1, s0

# c.mva23s: sreg1 = 1; sreg2 = 3;
mv (a2, a3), (s1, s3) ; # mv a2, s1; mv a3, s3
----

== Proposal: Generic pair move

A limitation of the other proposal is that it is tied specifically to the UABI. Therefore it may not be effective for the EABI, or any future ABI which may be applied to RISC-V. This is an attempt to design a generic pair move instruction which is *not* tied to the ABI. One big reason why this has lower benefit than hoped for is the discontinuity between `s1 (x9)` and `s2 (x18)` which is very UABI specific and these isntructions take much more encoding space than c.mv01as0[37]/c.mv23as0[37] above.

[#proposed-16bit-encodings_generic]
.proposed 16-bit encodings for generic pair moves
[width="100%",options=header]
|==================================================================================================
| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6  | 5  | 4 | 3 | 2 | 1 | 0 |instruction |code points  
18+|*the suffixes on the mnemonics show the different versions, at most one will be implemented called* `c.mvp`
18+|destination and source pairs can be even/odd pairs and source pair can be swapped
| ? 5+| rdp[4:0]       5+| rsp[4:0]   |swap               4+| ???? | C.MVP_EO_EO_SN | 1<<11
18+|destination pair is even only (rdp[0]=0) source pair is odd/even pairs and source pair can be swapped
| ? 4+| rdp[4:1]    |? 5+| rsp[4:0]   |swap               4+| ???? | C.MVP_E_EO_SN  | 1<<10
18+|destination and source pairs are be even pairs only (rdp[0]=0,rsp[0]=0) and source pair can be swapped
| ? 4+| rdp[4:1]    |? 4+| rsp[4:1] |?|swap               4+| ???? | C.MVP_E_E_SN   | 1<<9
18+|destination and source pairs are be even pairs only (rdp[0]=0,rsp[0]=0) and source pair is always swapped (swap=1)
| ? 4+| rdp[4:1]    |? 4+| rsp[4:1] |?|?                  4+| ???? | C.MVP_E_E_S    | 1<<8
|==================================================================================================

the pseudo-code code is as follows:

[source,sourceCode,text]
----
if (swap) {
src1=rsp+1; src2=rsp;
} else {
src1=rsp; src2=rsp+1;
}
dst1=rdp; dst2=rdp+1;

asm("mv x%s, x%s", dst1, src1);
asm("mv x%s, x%s", dst2, src2);

----

for example:

[source,sourceCode,text]
----
//even/odd destination pair, source pair is always even/odd, swapped
c.MVP rdp = 2, rsp = 4, swap = 1
mv x2, x5; mv x3, x4; #; mv(x2,x3), (x5,x4)
----

== Implementation

Clearly multi-move requires two write ports. The instruction(s) can be sequenced to avoid adding the extra write port. 
This is invisible to software as the whole instruction must execute atomically.

== Benchmark results

See https://github.com/riscv/riscv-code-size-reduction/blob/master/ISA%20proposals/Huawei/README.adoc[results here]

== Toolchain implementation

This is designed to be a link-time optimisation. The linker will combine suitable `mv` instructions.

== 32-bit form

Not yet specified. The 32-bit form must move more than 2 registers or there is no advantage over 2 `c.mv` instructions.
