= RISC-V Push/Pop Extension (UABI only version)
Version 0.1
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 4
:numbered:
:xrefstyle: short
:le: &#8804;
:rarr: &#8658;

This document describes：

* 32-bit encodings for `PUSH/PUSH.[FDQ]`, `POP/POP.[FDQ]` and `POPRET/POPRET.[FDQ]`
* 16-bit encodings for `C.PUSH, C.POP` and `C.POPRET` instructions 

The instructions are defined for RV32, RV64 and RV128 architectures I variants only, using the UABI. 

Future revisions may include:

* The E variant
* EABI support

These instructions are to reduce the code-size of function prologues and epilogues by using a single encoding to replace a sequence of instructions. 
They are designed to replace common function prologue/epilogue sequences, but will not replace all possible cases. 

== Open issues

it's better to list these first, as they are resolved I'll update the proposal

* whether to allow the x-register syntax? It breaks up the ranges which is annoying as s1 and s2 do not map to consecutive registers, so it's excluded at the moment

== Assembler Syntax

[source,sourceCode,text]
----
//these encodings may be 16-bit or 32-bit depending upon the parameters
push           {<xreg_list>},  -<stack_adjustment>
pop            {<xreg_list>},   <stack_adjustment> 
popret         {<xreg_list>},   <stack_adjustment> 

//these encodings are 32-bit as F registers are included in the list, the length of the F registers is specified in the encoding
push.[fdq]     {<fxreg_list>}, -<stack_adjustment> 
pop.[fdq]      {<fxreg_list>},  <stack_adjustment> 
popret.[fdq]   {<fxreg_list>},  <stack_adjustment> 
----

[NOTE]

  It is required to hard-code the length of the F registers in the opcode, and not just save/restore the whole register. We must allow code compiled for the F-extension
  to run on a  core which supports D and posibly Q, and for code compiled for the D-extension to run on a core which supports Q.
  If we don't explicitly state the F register width and always store the whole register, then the registers will be stored at different addresses to the ones expected 
  by the compiler. An alternative would be to use `misa.[FDQ]`
  to directly control the behaviour and so set `misa.[DQ]=0` when running F code. Nothing else in the architecture requires this, so it seems unreasonable to 
  add this requirement here.

. `PUSH` pushes the registers specified in `[f]xreg_list` to the stack, and then adjust the stack pointer by the `stack_adjustment`.
. `POP` pops the registers in `[f]xreg_list to the stack` from the stack, and then adjusts the stack pointer by the `stack_adjustment`.
. `POPRET` has the same behaviour as `POP`, followed by `RET`.

32-bit and 16-bit forms are available, the assembler should choose the 16-bit form if the parameters permit and the C extension is implemented.

The registers in `xreg_list` are in a comma separated list. The list must not be empty.

[source,sourceCode,text]
----
<reg_list>   ::= <xreg_list> | <fxreg_list>
<xreg_list>  ::= <ra> "," <xreg_range> | <ra> | <xreg_range>
<fxreg_list> ::= <ra> "," <xreg_range> ", " <freg_range> | <ra> "," <freg_range> | <xreg_range> "," <freg_range> | <freg_range>
<xreg_range> ::= <s0>  | <s0-sN>   (where `N` is in the range [1, 11])
<freg_range> ::= <fs0> | <fs0-fsM> (valid values of `M` are 0,1,2,3,5,8,11)
----

For the 16-bit encodings

. `ra` must be included
. `s0-sN` may be included, valid values of `N` are 0,1,2,3,5,8,11
. `fs0-fsM` must not be included
. the `stack_adjustment` must be no more than the total memory required for `xreg_list`, rounded up to a multiple of 16-bytes, plus an addition (0..7)*16-bytes.

[NOTE]
  To save encoding space some opcodes do not allow the full range of `spimm` which reduces the possible `stack adjustment` range further, see <<#16bitencodings>>

For the 32-bit encodings

. the `stack_adjustment` must be no more than the total memory required for `reg_list`, rounded up to a multiple of 16-bytes, plus an additional (0..15)*16-bytes.

For example

. `push   {ra,s0-s2}, -64` can use a 16-bit encoding
. `push.f {ra,s0-s2, fs0}, -64` must use a 32-bit encoding as `fs0` is in the register list
. `push   {ra,s0-s2}, -256` must use a 32-bit encoding as the `stack_adjustment` is out of range

To be a legal encoding:

1.  The stack adjustment must be negative for all `PUSH` variants and positive for a `POP[RET]` variants
2.  The stack adjustment must be in range (see <<spimm>>) and must be a multiple of 16
3.  The register list must be valid (see above)
4.  If any F registers are included in the list there must be a `.[fdq]` suffix
5.  It there is a `.[fdq]` suffix, there must be F registers in the list

[NOTE]
  When moving from accessing `x` registers to `f` registers there may be a gap as the registers may be different widths, and all registers must be aligned in memory

== Determining XLEN and FLEN to decode and execute the instructions

The width of `x` registers in the register list depends upon XLEN and so `misa.MXL`. From the ELF file header, XLEN is determined by the following flags:

* ELFCLASS64 for RV64
* ELFCLASS32 for RV32 

[NOTE]

  I don't think there's an ELFCLASS128 for RV128

If using a debugger then `misa.MXL` can be read, if XLEN is not known for the core.

FLEN is explicitly specified in the opcode as the presence of any F registers requires a `.[fdq]` suffix on the opcode.

Follow this link for details of the https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#file-header[ELF file header]

== Implementation of sequenced instructions

The sequences below show the required architectural state updates only, the hardware implementation is not specified here. 

Note that each step of the example sequence can be executed as a standard RISC-V 32-bit encoding, so that it is possible to convert the sequences into a sequence of standard instructions. 

Because the sequences include load and store operations, they may take any exception caused by executing loads or stores such as page faults, PMP faults, debug triggers. 

Additionally interrupts and debug halts may be received during execution. 

Handling of these cases is implementation defined but it is recommended that the standard interrupt/exception/debug handlers can be used without modification.

=== PUSH Pseudo-code

All variants of the `PUSH` instruction store the set of registers from `reg_list` to consecutive memory locations, and decrement the stack pointer.
The pseudo-code uses assembly inserts so that it can use `fsw/fsd` etc.

[NOTE]
  `stack_adjustment` is negative.

[source,sourceCode,text]
----
if (misa.MXL==1) {bytes=4;}
if (misa.MXL==2) {bytes=8;}
else             {bytes=16;}
addr=sp;
sp+=stack_adjustment; //decrement
if (ra) {
  addr-=bytes;
  switch(bytes) {
    4:  asm("sw ra, 0(addr)");
    8:  asm("sd ra, 0(addr)");
    16: asm("sq ra, 0(addr)");
  }
}
for(i in xreg_list)  {
  addr-=bytes;
  switch(bytes) {
    4:  asm("sw s[i], 0(addr)");
    8:  asm("sd s[i], 0(addr)");
    16: asm("sq s[i], 0(addr)");
  }
}
if (freq_list) {
  switch (opcode) {
    //if FLEN > XLEN, then get the address back into alignment before saving the F registers
    "PUSH.D": while(addr% 8) {addr-=bytes;}
    "PUSH.Q": while(addr%16) {addr-=bytes;}
  }
  for(i in freg_list)  {
    addr-=bytes;
    switch (opcode) {
      "PUSH.F": asm("fsw fs[i], 0(addr)");
      "PUSH.D": asm("fsd fs[i], 0(addr)");
      "PUSH.Q": asm("fsq fs[i], 0(addr)");
    }
  }
}
----

=== POP[RET] Pseudo-code

A `POP` instruction loads the set of registers from `reg_list` from consecutive memory locations, and then increments the stack pointer. 
The pseudo-code uses assembly inserts so that it can use `flw/fld/ret`.

[NOTE]
  `stack_adjustment` is positive.

[source,sourceCode,text]
----
if (misa.MXL==1) {bytes=4;}
if (misa.MXL==2) {bytes=8;}
else             {bytes=16;}
addr=sp+stack_adjustment;
if (ra) {
  addr-=bytes;
  switch(bytes) {
    4:  asm("lw ra, 0(addr)");
    8:  asm("ld ra, 0(addr)");
    16: asm("lq ra, 0(addr)");

  }
}
for(i in xreg_list)  {
  addr-=bytes;
  switch(bytes) {
    4:  asm("lw s[i], 0(addr)");
    8:  asm("ld s[i], 0(addr)");
    16: asm("lq s[i], 0(addr)");
  }
}
if (freq_list) {
  switch (opcode) {
    //if FLEN > XLEN, then get the address back into alignment before saving the F registers
    "PUSH.D": while(addr% 8) {addr-=bytes;}
    "PUSH.Q": while(addr%16) {addr-=bytes;}
  }
  for(i in freg_list)  {
    addr-=bytes;
    switch (opcode) {
      "PUSH.F": asm("flw fs[i], 0(addr)");
      "PUSH.D": asm("fld fs[i], 0(addr)");
      "PUSH.Q": asm("flq fs[i], 0(addr)");
    }
  }
}
sp+=stack_adjustment; //increment
if (opcode == "POPRET*) { 
   asm("ret");
}
----

== 32-bit Encodings

.proposed 32-bit encodings
[options="header",width="100%"]
|============================================================================
|31:30  |29:28|27:25   |24 |23:20  |19:15 |14:12 |11:7  |6:0     |name
|xx     |xx   |0000    |ra |rcount |spimm |000   |xxxxx |xxxxxxx |PUSH
|xx     |xx   |0000    |ra |rcount |spimm |001   |xxxxx |xxxxxxx |POP
|xx     |xx   |0000    |ra |rcount |spimm |010   |xxxxx |xxxxxxx |POPRET

|xx     |00   |frcount |ra |rcount |spimm |000   |xxxxx |xxxxxxx |PUSH.F
|xx     |00   |frcount |ra |rcount |spimm |001   |xxxxx |xxxxxxx |POP.F
|xx     |00   |frcount |ra |rcount |spimm |010   |xxxxx |xxxxxxx |POPRET.F

|xx     |01   |frcount |ra |rcount |spimm |000   |xxxxx |xxxxxxx |PUSH.D
|xx     |01   |frcount |ra |rcount |spimm |001   |xxxxx |xxxxxxx |POP.D
|xx     |01   |frcount |ra |rcount |spimm |010   |xxxxx |xxxxxxx |POPRET.D

|xx     |10   |frcount |ra |rcount |spimm |000   |xxxxx |xxxxxxx |PUSH.Q
|xx     |10   |frcount |ra |rcount |spimm |001   |xxxxx |xxxxxxx |POP.Q
|xx     |10   |frcount |ra |rcount |spimm |010   |xxxxx |xxxxxxx |POPRET.Q

10+|*reserved as `rcount` is out of range*
|xx     |xx   |xxxx    |x  |>12    |xxxx  |xxx   |xxxxx |xxxxxxx |*reserved*
10+|*reserved as no registers are specified*
|xx     |xx   |0000    |0  |0000   |xxxx  |xxx   |xxxxx |xxxxxxx |*reserved*
10+|*reserved as `flen` is out of range (bits [29:28]) and `frcount>0`*
|xx     |11   |>0     |0  |0000   |xxxx  |xxx    |xxxxx |xxxxxxx |*reserved*
|============================================================================

[NOTE]
  bits [29:28] are the `flen` field

=== Illegal instructions for the 32-bit encodings

The encoding takes the same behaviour as any floating point instruction if executed when disabled:

* if `frcount>0` and `misa.F==0`
* if `frcount>0` and `flen==1` and `misa.D==0`
* if `frcount>0` and `flen==2` and `misa.Q==0`

The following cases do not decode as `PUSH*/POP*/POPRET*`

* No registers are specified (`ra, rcount, frcount` are all zero)
* `rcount>12`
* `flen=3`

[#16bitencodings]
== 16-bit Encodings

.proposed 16-bit encodings
[options="header",width="100%"]
|=======================================================================
|15 |14 |13 |12 |11 |10 |9 |8 |7 |6 |5 |4 |3 |2 |1 |0 |instruction
3+|100|1|0|0|0 2+|rcount|0 |0 2+|00 | spimm 2+|00|C.POP
3+|100|1|0|0 3+|rcount|0 |1 3+|spimm 2+|00|C.POPRET
3+|100|1|0|0 3+|rcount|1 |0 3+|spimm 2+|00|C.PUSH
|=======================================================================

[NOTE]
  * For `C.POP`, `spimm[1]=0`, and `rcount[2]=0` are reserved, as these encodings  give minimal benefit
  * For `C.PUSH/C.POPRET`, if `rcount[2]=1` then `spimm[2]=0` as these encodings  give minimal benefit
  * These encodings remain *reserved* for the time being so we can add them later if they can be justified

== Encoding Fields

[#spimm]
=== `spimm` encoding field

The `stack_adjustment` field in the assembly syntax comprises of two components:

. the memory required for the registers in the list, rounded up to 16-bytes (using the `Align16` function below)
. additional stack space allocated for local variables, encoded in the `spimm` field

The 16-bit encoding allows up to 7 additional 16-byte blocks (as `spimm` has up to 3-bits), and the 32-bit encoding allows up to 31.

[NOTE]
  we may change the size of `spimm` in the 32-bit encoding once benchmarking work has completed

[source,sourceCode,text]
----
total_register_bytes = number_of_registers_in_reg_list * XLEN / 8
stack_adjustment = Align16(total_register_bytes) + 16*spimm
----

=== `ra, frcount, rcount` for the 32-bit encodings

The registers in the `reg_list` are controlled by these three fields

[#32bit-ra]
.`ra` field
[options="header"]
|====================================
|ra      | ABI names               
| 0      |none                     
| 1      |ra
|====================================

[#32bit-frcount]
.`frcount` values for the 32-bit encodings
[options="header"]
|=====================
|frcount | ABI names  
| 0      |none        
| 1      |fs0         
| 2      |fs0-fs1     
| 3      |fs0-fs2     
| 4      |fs0-fs3     
| 5      |fs0-fs5     
| 6      |fs0-fs8     
| 7      |fs0-fs11     
|=====================

[NOTE]
  We save 1-bit of encoding space by grouping the floating point registers

[#32bit-rcount]
.`rcount` field values for the 32-bit encodings
[options="header"]
|==========================
|rcount  | ABI names      
| 0      |none       
| 1      |s0
| 2      |s0-s1
| 3      |s0-s2
| 4      |s0-s3
| 5      |s0-s4
| 6      |s0-s5
| 7      |s0-s6
| 8      |s0-s7
| 9      |s0-s8
| 10     |s0-s9
| 11     |s0-s10
| 12     |s0-s11
| 13-15  | *reserved*
|==========================

=== `rcount` for the 16-bit encodings

[#rcount-table]
.`rcount` values for the 16-bit encodings
[options="header",width=100%]
|============================
|rcount| ABI names
|0     |ra
|1     |ra, s0
|2     |ra, s0-s1
|3     |ra, s0-s2
2+|Following options for `C.PUSH/C.POPRET` only
|4     |ra, s0-s3
|5     |ra, s0-s5
|6     |ra, s0-s8
|7     |ra, s0-s11
|============================

== Benchmarking results

Using the `PUSH/POP` support in HCC (Huawei GCC branch) allows the full range of register lists in the 16-bit encodings, and up to 5-bits of `spimm`.

https://github.com/riscv/riscv-code-size-reduction/blob/master/ISA%20proposals/Huawei/push_pop_encoding_results.xlsx[This spreadsheet] shows the results across the whole benchmark suite to show which instructions were inferred (not broken down by benchmark).

The target for the 16-bit encodings has been to minimise encoding space while keeping ~ 95% of the cases on the benchmark suite (94.9% achieved)

The overall saving compared to -msave-restore is 4.8% using HCC (this result is subject to change as the benchmark suite is updated). Minimising the encoding space reduces this benefit to 4.6%.

[#results-table]
.16-bit encoding code-size benefit
[options="header",width=100%]
|==================================================================
|Instruction|percentage of calls from HCC|overall code-size saving
|All        | 94.9%                      | 4.6% (94.9% of 4.8%)
|`C.PUSH`   | 47.5%                      | 2.3%
|`C.POPRET` | 37.6%                      | 1.8%
|`C.POP`    | 9.8%                       | 0.5%
|==================================================================

== Assembly examples

=== C.PUSH RV32 UABI (16-byte aligned stack)

[source,sourceCode,text]
----
c.push  {ra, s0-s5}, -64
----

Encoding: rcount=5, spimm=2

Equivalent sequence:

[source,sourceCode,text]
----
addi sp, sp, -64;
sw  ra, 60(sp);
sw  s0, 56(sp); 
sw  s1, 52(sp);
sw  s2, 48(sp); 
sw  s3, 44(sp);
sw  s4, 40(sp); 
sw  s5, 36(sp);
----

=== C.PUSH RV32I UABI (16-byte aligned stack)

[source,sourceCode,text]
----
c.push {ra, s0-s1}, -32
----

Encoding: rcount=2, spimm=2

Equivalent sequence:

[source,sourceCode,text]
----
addi sp, sp, -32;
sw  ra, 28(sp);
sw  s0, 24(sp); 
sw  s1, 20(sp);
----

=== C.POP RV32I UABI (16-byte aligned stack)

[source,sourceCode,text]
----
c.pop   {ra, s0-s7}, 160
----

Encoding: rcount=6, spimm=7 

Equivalent sequence:

[source,sourceCode,text]
----
lw   ra, 156(sp);
lw   s0, 152(sp);  
lw   s1, 148(sp);  
lw   s2, 144(sp);  
lw   s3, 140(sp);  
lw   s4, 136(sp);  
lw   s5, 132(sp);  
lw   s6, 128(sp);  
lw   s7, 124(sp);  
lw   s8, 120(sp);  
addi sp, sp, 160
----

=== PUSH.F RV32 UABI (16-byte aligned stack)

[source,sourceCode,text]
----
push.f  {fs0, ra, s0-s4}, -64
----

Encoding: ra=1, rcount=5, frcount=1, flen=0, spimm=2 (16-byte aligned)

Micro operation sequence:

[source,sourceCode,text]
----
addi sp, sp, -64;
sw  ra,  28(sp);
sw  s0,  24(sp); 
sw  s1,  20(sp); 
sw  s2,  16(sp); 
sw  s3,  12(sp); 
sw  s4,   8(sp); 
fsw fs0,  4(sp)
----

=== PUSH.D RV64 UABI (16-byte aligned stack)

[source,sourceCode,text]
----
push.f  {fs0, ra, s0-s4}, -64
----

Encoding: ra=1, rcount=5, frcount=1, flen=1, spimm=0 (16-byte aligned)

Micro operation sequence:

[source,sourceCode,text]
----
addi sp, sp, -64;
sw  ra,  56(sp);
sw  s0,  48(sp); 
sw  s1,  40(sp);
sw  s2,  32(sp); 
sw  s3,  24(sp);
sw  s4,  16(sp); 
fsd fs0,  8(sp)
----

=== PUSH.D RV64 UABI (16-byte aligned stack)

[source,sourceCode,text]
----
push.d  {fs0-fs7}, -128
----

Encoding: rcount=0, frcount=12, flen=2, spimm=2 (16-byte aligned)

Micro operation sequence:

[source,sourceCode,text]
----
addi sp, sp, -128; 
fsd  fs0, 120(sp);
fsd  fs1, 112(sp); 
fsd  fs2, 104(sp);
fsd  fs3,  96(sp); 
fsd  fs5,  88(sp); 
fsd  fs4,  80(sp);
fsd  fs6,  72(sp);
fsd  fs7,  64(sp); 
fsd  fs8,  56(sp); 
fsd  fs9,  48(sp); 
fsd  fs10, 40(sp); 
fsd  fs11, 32(sp); 
----

=== POP RV32I UABI (16-byte aligned stack)

[source,sourceCode,text]
----
pop   {ra, s0-s9}, 256
----

Encoding: ra=1, rcount=10, frcount=0, spimm=13 (16-byte aligned)

Micro operation sequence:

[source,sourceCode,text]
----
lw   ra, 252(sp);
lw   s0, 248(sp);
lw   s1, 244(sp);  
lw   s2, 240(sp)
lw   s3, 236(sp);  
lw   s4, 232(sp);
lw   s5, 228(sp);  
lw   s6, 224(sp)
lw   s7, 220(sp);  
lw   s8, 216(sp);
lw   s9, 212(sp);  
addi sp, sp, 256
----

=== POPRET.F RV32I UABI (16-byte aligned stack)

[source,sourceCode,text]
----
popret.f   {fs0-fs1, ra, s0-s3}, 32
----

Encoding: ra=1, rcount=4, frcount=2, flen=1, spimm=0 (16-byte aligned)

Micro operation sequence:

[source,sourceCode,text]
----
lw   ra, 28(sp);
lw   s0, 24(sp);
lw   s1, 20(sp);  
lw   s2, 16(sp);
lw   s3, 12(sp);  
flw  fs0, 8(sp);
flw  fs1, 4(s0);  
addi sp, sp, 32; 
ret
----

