<<<
[#insns-c_mvs07a01,reftext="c.mvas07a01: move a0-a1 into two s0-s7 registers, 16-bit encoding"]
=== c.mvs07a01

Synopsis::
Move two s0-s7 registers into a0-a1, 16-bit encoding

Mnemonic::
c.mvas07a01 _sreg1, sreg2_

Encoding (RV32, RV64, RV128)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1,      attr: ['OP=C1'] },
    { bits:  3, name: 'sreg2',  attr: [] },
    { bits:  2, name: 0x3,      attr: [] },
    { bits:  3, name: 'sreg1',  attr: [] },
    { bits:  8, name: 0x27,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

Syntax::

[source,sail]
--
c.mvas07a01 sreg1, sreg2
--

Description::
This instruction moves _a0_ into _sreg1_ and _a1_ into _sreg2_. The execution is atomic, so it is not possible to observe state where only one of _sreg1_ or _sreg2_ have been updated.

<<<
Field decoding::

[#c_mvas07a01_sreg_decoding]
._sreg_ decoding
[options="header",width=60%]
|==============
|sreg*   |xreg 
|0       |x8   
|1       |x9   
|2       |x18  
|3       |x19  
|4       |x20  
|5       |x21  
|6       |x22  
|7       |x23  
|==============

The encoding has two _sreg_ number specifiers to save encoding space. 

[NOTE]

  This instruction does not directly expand to a single 32-bit encoding.

Prerequisites::
The C-extension must also be configured.

<<<

Operation::
[source,sail]
--
//This is not SAIL, it's pseudo-code. The SAIL hasn't been written yet.

if (sreg1==sreg2) {take_illegal_instruction_exception();}

xreg1 = {sreg1[2:1]>0,sreg1[2:1]==0,sreg1[2:0]}
xreg2 = {sreg2[2:1]>0,sreg2[2:1]==0,sreg2[2:0]}

X[sreg1] = X[10]
X[sreg2] = X[11]
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

|Zces (<<Zces>>)
|0.51
|Plan
|===
