<<<
[#insns-c_popretz_l,reftext="c.popretz.l: Destroy stack frame: pop registers, deallocate stack frame, return zero."]
=== c.popretz.l

Synopsis::
Destroy stack frame: load ra and 4 to 12 saved registers from the stack frame, deallocate the stack frame, move zero into a0, return to ra.

Mnemonic::
c.popretz.l

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: [] },
    { bits:  3, name: 'rlist3', attr: [] },
    { bits:  2, name: 0x3,      attr: []},
    { bits:  3, name: 'spimm\[6:4\]',  attr: [] },
    { bits:  6, name: 0x2b,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

Assembly Syntax::

[source,sail]
--
c.popretz {reg_list_5_13},  -stack_adj
c.popretz {xreg_list_5_13}, -stack_adj
--

include::pushpop_l_vars.adoc[]

Description::
This instruction pop (loads) the registers in _reg_list_5_13_ from stack memory,
 adjusts the stack pointer by _stack_adj_, moves zero into a0 and then returns.

include::pushpop_extra_info.adoc[]
include::c_pop_popret_l_loads_pseudo_code.adoc[]
include::c_popretz_pseudo_code.adoc[]

<<<

RV32 Assembly example::

[source,sail]
--
c.popretz {ra, s0-s3}, 48
--

Encoding: _rlist2_=0, _spimm_=1

The equivalent sequence for pseudo-code evaluation and an interrupt safe assembly sequence is:

[source,sail]
--
lw   s3, 44(sp);
lw   s2, 40(sp);  
lw   s1, 36(sp);  
lw   s0, 32(sp);  
lw   ra, 28(sp);  
addi sp, sp, 48;
li   a0, 0;
ret;
--

RV32 Assembly example::

[source,sail]
--
c.popretz {ra, s0-s4}, 64
--

Encoding: _rlist2_=1, _spimm_=2

The equivalent sequence for pseudo-code evaluation and an interrupt safe assembly sequence is:

[source,sail]
--
lw   s4, 60(sp);
lw   s3, 56(sp);
lw   s2, 52(sp);  
lw   s1, 48(sp);  
lw   s0, 44(sp);  
lw   ra, 40(sp);  
addi sp, sp, 64;
li   a0, 0;
ret;
--

include::Zces_footer.adoc[]

