<<<
[#insns-c_popretz,reftext="c.popretz: Destroy stack frame: pop registers, deallocate stack frame, return zero."]
=== c.popretz

Synopsis::
Destroy stack frame: load ra and 0 to 12 saved registers from the stack frame, deallocate the stack frame, move zero into a0, return to ra.

Mnemonic::
c.popretz

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: [] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x1c,            attr: [] },
    { bits:  3, name: 0x5,             attr: [] },
],config:{bits:16}}
....

[NOTE]

  _rlist_ values 0 to 3 are reserved for a future EABI variant called _c.popretz.e_


Assembly Syntax::

[source,sail]
--
c.popretz {reg_list},  stack_adj
c.popretz {xreg_list}, stack_adj
--

include::pushpop_vars.adoc[]

<<<

Description::
This instruction pop (loads) the registers in _reg_list_ from stack memory,
 adjusts the stack pointer by _stack_adj_, moves zero into a0 and then returns to _ra_.

include::pushpop_extra_info.adoc[]
include::c_pop_popret_loads_pseudo_code.adoc[]
include::c_popretz_pseudo_code.adoc[]

<<<

RV32 Assembly example::

[source,sail]
--
c.popretz {ra}, 16
--

Encoding: _rlist_=4, _spimm_=0

The equivalent interrupt safe assembly sequence is:

[source,sail]
--
lw   ra, 12(sp);
li   a0, 0;
addi sp, sp, 16;
ret;
--

RV32 Assembly example::

[source,sail]
--
c.popretz {ra, s0-s2}, 48
--

Encoding: _rlist_=7, _spimm_=2

The equivalent interrupt safe assembly sequence is:

[source,sail]
--
lw   s2, 44(sp);
lw   s1, 40(sp);  
lw   s0, 36(sp);  
lw   ra, 32(sp);  
li   a0, 0;
addi sp, sp, 48;
ret;
--

RV32 Assembly example::

[source,sail]
--
c.popretz {ra, s0-s3}, 48
--

Encoding: _rlist_=8, _spimm_=1

The equivalent interrupt safe assembly sequence is:

[source,sail]
--
lw   s3, 44(sp);
lw   s2, 40(sp);  
lw   s1, 36(sp);  
lw   s0, 32(sp);  
lw   ra, 28(sp);  
li   a0, 0;
addi sp, sp, 48;
ret;
--

<<<

RV32 Assembly example::

[source,sail]
--
c.popretz {ra, s0-s4}, 64
--

Encoding: _rlist_=9, _spimm_=2

The equivalent interrupt safe assembly sequence is:

[source,sail]
--
lw   s4, 60(sp);
lw   s3, 56(sp);
lw   s2, 52(sp);  
lw   s1, 48(sp);  
lw   s0, 44(sp);  
lw   ra, 40(sp);  
li   a0, 0;
addi sp, sp, 64;
ret;
--

include::Zces_footer.adoc[]

