<<<
[#insns-c_popret,reftext="c.popret: Destroy stack frame: pop registers, deallocate stack frame, return."]
=== c.popret

Synopsis::
Destroy stack frame: load ra and 0 to 3 saved registers from the stack frame, deallocate the stack frame, return to ra.

Mnemonic::
c.popret

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: [] },
    { bits:  2, name: 'rlist2', attr: [] },
    { bits:  3, name: 0x3,      attr: []},
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  1, name: 0x0,      attr: []},
    { bits:  6, name: 0x2b,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

Assembly Syntax::

[source,sail]
--
c.popret {reg_list_1_4},  stack_adj
c.popret {xreg_list_1_4}, stack_adj
--

include::variable_def.adoc[]
include::pushpop_vars.adoc[]

Description::
This instruction pop (loads) the registers in _reg_list_1_4_ from stack memory,
 adjusts the stack pointer by _stack_adj_ and then returns.

include::pushpop_extra_info.adoc[]
include::c_pop_popret_loads_pseudo_code.adoc[]
include::c_popret_pseudo_code.adoc[]

<<<

RV32 Assembly example::

[source,sail]
--
c.popret {ra, s0-s2}, 48
--

Encoding: _rlist2_=3, _spimm_=2

The equivalent interrupt safe assembly sequence is:

[source,sail]
--
lw   s2, 44(sp);
lw   s1, 40(sp);  
lw   s0, 36(sp);  
lw   ra, 32(sp);  
addi sp, sp, 48;
ret;
--

RV32 Assembly example::

[source,sail]
--
c.popret {ra}, 16
--

Encoding: _rlist2_=0, _spimm_=0

The equivalent interrupt safe assembly sequence is:

[source,sail]
--
lw   ra, 12(sp);
addi sp, sp, 16;
ret;
--

include::Zces_footer.adoc[]
