<<<
[#insns-c_pusha,reftext="c.pusha: Create stack frame: push registers, move A to S registers, allocate additional stack space."]
=== c.pusha

Synopsis::
Create stack frame: store ra and 1 to 3 saved registers to the stack frame, move arguments into saved registers, optionally allocate additional stack space.

Mnemonic::
c.pusha

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: [] },
    { bits:  2, name: 'rlist2', attr: [] },
    { bits:  3, name: 0x3,      attr: []},
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  1, name: 0x0,      attr: []},
    { bits:  6, name: 0x2a,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

[NOTE]

  _rlist2=0_ is reserved

Assembly Syntax::

[source,sail]
--
c.push {reg_list_2_4},   {areg_list_1_3},  -stack_adj
c.push {xreg_list_2_4>}, {xareg_list_1_3}, -stack_adj
--

include::variable_def.adoc[]

[source,sail]
--
switch (rlist2) {
  case 1: {areg_list_1_3="a0";    xareg_list_1_3="x10";}
  case 2: {areg_list_1_3="a0-s1"; xareg_list_1_3="x10-x11";}
  case 3: {areg_list_1_3="a0-s2"; xareg_list_1_3="x10-x12";}
}
--

[source,sail]
--
switch (rlist2) {
  case 1: {reg_list_2_4="ra, s0";    xreg_list_2_4="x1, x8";}
  case 2: {reg_list_2_4="ra, s0-s1"; xreg_list_2_4="x1, x8-x9";}
  case 3: {reg_list_2_4="ra, s0-s2"; xreg_list_2_4="x1, x8-x9, x18";}
}
stack_adj      = stack_adj_base + spimm[5:4] * 16;
--

RV32:
[source,sail]
--
stack_adj_base = 16;

Valid values:
stack_adj      = [16|32|48|64];
--

<<<

RV64:
[source,sail]
--
switch (rlist2) {
  case 0..1: stack_adj_base=16;
  case 2..3: stack_adj_base=32;
}

Valid values:
switch (rlist2) {
  case 0..1: stack_adj=[16|32|48|64|96];
  case 2..3: stack_adj=[32|48|64|96|112];
}
--

Description::
This instruction pushes (stores) the registers in _reg_list_2_4_ to stack memory, 
moves _areg_list_1_3_ into correspondingly numbered _s_ registers, 
and then adjusts the stack pointer by _-stack_adj_. 

include::pushpop_extra_info.adoc[]
include::c_pusha_stores_pseudo_code.adoc[]
include::c_pusha_pseudo_code.adoc[]

<<<

RV32 Assembly example::

[source,sail]
----
c.push  {ra, s0-s2}, {a0-a2}, -64
----

Encoding: _rlist2_=3, _spimm_=3

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, -64;
sw  s2, 60(sp);
sw  s1, 56(sp); 
sw  s0, 52(sp);
sw  ra, 48(sp); 
mv  s0, a0
mv  s1, a1
mv  s2, a2
----

The pseudo-code evaluates to:

[source,sail]
----
sw  s2, -4(sp);
sw  s1, -8(sp); 
sw  s0, -12(sp);
sw  ra, -16(sp); 
mv  s0, a0
mv  s1, a1
mv  s2, a2
addi sp, sp, -64;
----

<<<

RV32 Assembly example::

[source,sail]
----
c.push {ra, s0-s1}, {a0-a1}, -32
----

Encoding: _rlist2_=2, _spimm_=1

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, -32;
sw  s1, 28(sp);
sw  s0, 24(sp); 
sw  ra, 20(sp);
mv  s0, a0
mv  s1, a1
----

The pseudo-code evaluates to:

[source,sail]
----
sw  s1, -4(sp);
sw  s0, -8(sp); 
sw  ra, -12(sp);
mv  s0, a0
mv  s1, a1
addi sp, sp, -32;
----

include::Zces_footer.adoc[]

