<<<
[#insns-c_pusha,reftext="c.pusha: Create stack frame: push registers, move A to S registers, allocate additional stack space."]
=== c.pusha

Synopsis::
Create stack frame: store ra and 1 to 12 saved registers to the stack frame, move arguments into saved registers, optionally allocate additional stack space.

Mnemonic::
c.pusha

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: [] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x14,            attr: [] },
    { bits:  3, name: 0x5,             attr: [] },
],config:{bits:16}}
....

[NOTE]

  _rlist_ values 0 to 3 are reserved for a future EABI variant called _c.pusha.e_

[NOTE]

  _rlist_ value 4 is reserved, unlike for _c.push_, _c.pop_, _c.popret_, _c.popretz_

Assembly Syntax::

[source,sail]
--
c.push {reg_list},  {areg_list},  -stack_adj
c.push {xreg_list}, {xareg_list}, -stack_adj
--

include::variable_def.adoc[]

[source,sail]
--
RV32E:

switch (rlist){
  case  5: {reg_list="ra, s0";     areg_list="a0";    xareg_list="x10";}
  case  6: {reg_list="ra, s0-s1";  areg_list="a0-a1"; xareg_list="x10-x11";}
  default: take_illegal_instruction_exception();
}
--

[source,sail]
--
RV32I, RV64:

switch (rlist){
  case     5: {reg_list="ra, s0";     areg_list="a0";    xareg_list="x10";}
  case     6: {reg_list="ra, s0-s1";  areg_list="a0-a1"; xareg_list="x10-x11";}
  case 7..15: {reg_list="ra, s0-s2";  areg_list="a0-a2"; xareg_list="x10-x12";}
  default:    take_illegal_instruction_exception();
}
--

include::pushpop_vars.adoc[]

Description::
This instruction pushes (stores) the registers in _reg_list_ to stack memory, 
moves _areg_list_ into correspondingly numbered _s_ registers, 
and then adjusts the stack pointer by _-stack_adj_. 

include::pushpop_extra_info.adoc[]
include::c_push_stores_pseudo_code.adoc[]
include::c_pusha_pseudo_code.adoc[]

<<<

RV32I Assembly example::

[source,sail]
----
c.push  {ra, s0-s2}, {a0-a2}, -64
----

Encoding: _rlist_=7, _spimm_=3

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, -64;
sw  s2, 60(sp);
sw  s1, 56(sp); 
sw  s0, 52(sp);
sw  ra, 48(sp); 
mv  s0, a0;
mv  s1, a1;
mv  s2, a2;
----

RV32I Assembly example::

[source,sail]
----
c.push {ra, s0-s1}, {a0-a1}, -32
----

Encoding: _rlist_=6, _spimm_=1

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, -32;
sw  s1, 28(sp);
sw  s0, 24(sp); 
sw  ra, 20(sp);
mv  s0, a0;
mv  s1, a1;
----

RV32I Assembly example::

[source,sail]
----
c.push  {ra, s0-s3}, {a0-a2}, -64
----

Encoding: _rlist_=8, _spimm_=2

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, 64;
sw  s3, 60(sp);
sw  s2, 56(sp); 
sw  s1, 52(sp);
sw  s0, 48(sp); 
sw  ra, 44(sp); 
mv  s0, a0;
mv  s1, a1;
mv  s2, a2;
----

<<<

RV32I Assembly example::

[source,sail]
----
c.push {ra, s0-s11}, {a0-a2}, -112
----

Encoding: _rlist_=15, _spimm_=3

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, 112;
sw  s11, 108(sp);
sw  s10, 104(sp); 
sw  s9,  100(sp);
sw  s8,   96(sp);
sw  s7,   92(sp);
sw  s6,   88(sp);
sw  s5,   84(sp);
sw  s4,   80(sp);
sw  s3,   76(sp);
sw  s2,   72(sp);
sw  s1,   68(sp);
sw  s0,   64(sp);
sw  ra,   60(sp);
mv  s0, a0;
mv  s1, a1;
mv  s2, a2;
----

include::Zces_footer.adoc[]
