<<<
[#insns-c_push,reftext="c.push: Create stack frame: push registers, allocate additional stack space."]
=== c.push

Synopsis::
Create stack frame: store ra and 0 to 3 saved registers to the stack frame, optionally allocate additional stack space.

Mnemonic::
c.push

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: [] },
    { bits:  2, name: 'rlist2', attr: [] },
    { bits:  3, name: 0x3,      attr: []},
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  1, name: 0x1,      attr: []},
    { bits:  6, name: 0x2a,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

Assembly Syntax::

[source,sail]
--
c.push {reg_list_1_4},  -stack_adj
c.push {xreg_list_1_4}, -stack_adj
--

include::variable_def.adoc[]
include::pushpop_vars.adoc[]

<<<
Description::
This instruction pushes (stores) the registers in _reg_list_1_4_ to the memory below the stack pointer, 
and then creates the stack frame by decrementing the stack pointer by _stack_adj_, including any additional stack space requested by the value of _spimm_.

include::pushpop_extra_info.adoc[]
include::c_push_stores_pseudo_code.adoc[]
include::c_push_pseudo_code.adoc[]

<<<

RV32 Assembly example::

[source,sail]
----
c.push  {ra, s0-s2}, -64
----

Encoding: _rlist2_=3, _spimm_=3

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, -64;
sw  s2, 60(sp);
sw  s1, 56(sp); 
sw  s0, 52(sp);
sw  ra, 48(sp); 
----

The pseudo-code evaluates to:

[source,sail]
----
sw  s2, -4(sp);
sw  s1, -8(sp); 
sw  s0, -12(sp);
sw  ra, -16(sp); 
addi sp, sp, -64;
----

<<<

RV32 Assembly example::

[source,sail]
----
c.push {ra, s0-s1}, -32
----

Encoding: _rlist2_=2, _spimm_=1

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, -32;
sw  s1, 28(sp);
sw  s0, 24(sp); 
sw  ra, 20(sp);
----

The pseudo-code evaluates to:

[source,sail]
----
sw  s1, -4(sp);
sw  s0, -8(sp); 
sw  ra, -12(sp);
addi sp, sp, -32;
----

include::Zces_footer.adoc[]
