<<<
[#insns-c_push_areg_list,reftext="c.push: push registers to stack memory, 16-bit encoding"]
=== c.push

Synopsis::
Push registers to stack memory, 16-bit encoding

Mnemonic::
c.push _{reg_list}, {areg_list}, -stack_adj_

Encoding (RV32, RV64, RV128)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0,      attr: ['OP=C0'] },
    { bits:  3, name: 'rlist3', attr: ['reg_list'] },
    { bits:  2, name: 0x2,      attr: []},
    { bits:  3, name: 'spimm0_5\[6:4\]',  attr: [] },
    { bits:  6, name: 0x23,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

[NOTE]

  _spimm0_5_ is only valid for _c.push_ for values 0-5. Values 6 and 7 do _not_ decode as _c.push_.

Syntax::

[source,sail]
--
c.push {<reg_list_16u> | <xreg_list_16u>}, {<areg_list>), -<stack_adj>
--

The variables used in the syntax are defined below.

[source,sail]
--
<reg_list_16u> ::= <ra> ["," <s0>  | <s0-sN> ] (where N is 1,2,3,5,7,11)

if (<reg_list_16u>=="ra")          <xreg_list_16u>="x1"
if (<reg_list_16u>=="ra, s0")      <xreg_list_16u>="x1, x8"
if (<reg_list_16u>=="ra, s0-s1")   <xreg_list_16u>="x1, x8-x9"
if (<reg_list_16u>=="ra, s0-s2")   <xreg_list_16u>="x1, x8-x9, x18"
if (<reg_list_16u>=="ra, s0-sN")   <xreg_list_16u>="x1, x8-x9, x18-xM" (where M=N+16 and N is 3,5,7,11)
 
if (<reg_list_16u>=="ra")          <areg_list>=""
if (<reg_list_16u>=="ra, s0")      <areg_list>="a0"
if (<reg_list_16u>=="ra, s0-sN")   <areg_list>="a0-aP" (where N is 1,2,3,5,7,11; if (N<4) P=N; else P=3;)

if (<reg_list_16u>=="ra")          <stack_adj>=[16|32|48|64|96]
if (<reg_list_16u>=="ra, s0")      <stack_adj>=[16|32|48|64|96]
if (<reg_list_16u>=="ra, s0-s1")   <stack_adj>=[16|32|48|64|96]
if (<reg_list_16u>=="ra, s0-s2")   <stack_adj>=[16|32|48|64|96]
if (<reg_list_16u>=="ra, s0-s3")   <stack_adj>=[32|48|64|96|112]
if (<reg_list_16u>=="ra, s0-s5")   <stack_adj>=[32|48|64|96|112]
if (<reg_list_16u>=="ra, s0-s7")   <stack_adj>=[48|64|96|112|128]
if (<reg_list_16u>=="ra, s0-s11")  <stack_adj>=[64|96|112|128|144]
--

Description::
This instruction pushes (stores) the registers in _reg_list_ to stack memory, moves _areg_list_ into similarly numbered _s_ registers, and then adjusts the stack pointer by _-stack_adj_. 
For further information see <<insns-pushpop>>.

Field decoding::

The mapping from the _rlist3_ and _spimm0_5_ fields in the encoding are as shown below.

[#c_push_areg_list_rlist3_decode]
._rlist3_ decoding 
[options="header",width=60%]
|============================
|rlist3  |reg_list_16u |stack_adj_base
|0       |ra           |16
|1       |ra, s0       |16
|2       |ra, s0-s1    |16
|3       |ra, s0-s2    |16
|4       |ra, s0-s3    |32
|5       |ra, s0-s5    |32
|6       |ra, s0-s7    |48
|7       |ra, s0-s11   |64
|============================

_stack_adj_base_ covers enough 16-byte blocks of memory to cover the registers in _reg_list_16u_. 

_spimm_0_5_ is used to allocate extra stack space in 16-byte blocks. 

The total stack adjustment is calculated as shown.

[source,sail]
--
stack_adj = stack_adj_base+spimm0_5[6:4]*16
--

[NOTE]
  _spimm0_5_ is only valid for values 0-5.

Prerequisites::
The C-extension must also be configured.

32-bit equivalent::
<<insns-push_areg_list>>

<<<

Operation::
[source,sail]
--
//This is not SAIL, it's pseudo-code. The SAIL hasn't been written yet.

//RV64/RV128 must have a 16-byte aligned sp
if (misa.MXL>=2 && sp[3:0]) {take_illegal_instruction_exception();}
//RV32I might be using the EABI (8-byte alignment) or UABI (16-byte alignment, so in hardware we can only check for 8)
if (misa.MXL==1 && sp[2:0]) {take_illegal_instruction_exception();}

if (misa.MXL==1) {bytes=4;}
if (misa.MXL==2) {bytes=8;}
else             {bytes=16;}
addr=sp-bytes;
switch(bytes) {
  4:  asm("sw ra, 0(addr)");
  8:  asm("sd ra, 0(addr)");
  16: asm("sq ra, 0(addr)");
}
for(i=31;i>=0;i--)  {
  //if register i is in xreg_list
  if (xreg_list[i]) {
    addr-=bytes;
    switch(bytes) {
      4:  asm("sw s[i], 0(addr)");
      8:  asm("sd s[i], 0(addr)");
      16: asm("sq s[i], 0(addr)");
    }
  }
}
//The sequence must be uninterruptible from this point
if (areg_list[a0]) asm("mv s0, a0");
if (areg_list[a1]) asm("mv s1, a1");
if (areg_list[a2]) asm("mv s2, a2");
if (areg_list[a3]) asm("mv s3, a3");
  
sp+=stack_adjustment; //decrement
--

<<<

Assembly examples::

[source,sail]
----
c.push  {ra, s0-s5}, {a0-a3}, -64
----

Encoding: _rlist3_=5, _spimm0_5[6:4]_=2

Equivalent sequence:

[source,sail]
----
sw  s5, -4(sp);
sw  s4, -8(sp); 
sw  s3, -12(sp);
sw  s2, -16(sp); 
sw  s1, -20(sp);
sw  s0, -24(sp); 
sw  ra, -28(sp);
mv  s0, a0
mv  s1, a1
mv  s2, a2
mv  s3, a3
addi sp, sp, -64;
----

[source,sail]
----
c.push {ra, s0-s1}, {a0-a1}, -32
----

Encoding: _rlist3_=2, _spimm0_5[6:4]_=1

Equivalent sequence:

[source,sail]
----
sw  s1, -4(sp);
sw  s0, -8(sp); 
sw  ra, -12(sp);
mv  s0, a0
mv  s1, a1
addi sp, sp, -32;
----

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

|Zces (<<Zces>>)
|0.52
|Stable
|===
