<<<
[#insns-c_pusha_l,reftext="c.pusha.l: Create stack frame: push registers, move A to S registers, allocate additional stack space."]
=== c.pusha.l

Synopsis::
Create stack frame: store ra and 4 to 12 saved registers, move argument registers into saved registers, optionally allocate additional stack space.

Mnemonic::
c.pusha.l

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: [] },
    { bits:  3, name: 'rlist3', attr: [] },
    { bits:  2, name: 0x2,      attr: []},
    { bits:  3, name: 'spimm\[6:4\]',  attr: [] },
    { bits:  6, name: 0x2a,     attr: ['FUNCT6'] },
],config:{bits:16}}
....

Assembly Syntax::

[source,sail]
--
c.push {reg_list_5_13},  {a0-a3},   -stack_adj
c.push {xreg_list_5_13}, {x10-x13}, -stack_adj
--

include::pushpop_l_vars.adoc[]

Description::
This instruction pushes (stores) the registers in _reg_list_5_13_ to stack memory, 
moves _a0-a3_ into correspondingly numbered _s_ registers, 
and then adjusts the stack pointer by _-stack_adj_. 

include::pushpop_extra_info.adoc[]
include::c_push_l_stores_pseudo_code.adoc[]
include::c_pusha_l_pseudo_code.adoc[]

<<<

RV32 Assembly example::

[source,sail]
----
c.push  {ra, s0-s3}, {a0-a3}, -64
----

Encoding: _rlist3_=0, _spimm_=2

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, 64;
sw  s3, 60(sp);
sw  s2, 56(sp); 
sw  s1, 52(sp);
sw  s0, 48(sp); 
sw  ra, 44(sp); 
mv  s0, a0
mv  s1, a1
mv  s2, a2
mv  s3, a3
----

RV32 Assembly example::

[source,sail]
----
c.push {ra, s0-s11}, {a0-a3}, -128
----

Encoding: _rlist3_=7, _spimm_=4

The equivalent interrupt safe assembly sequence is:

[source,sail]
----
addi sp, sp, 128;
sw  s11, 124(sp);
sw  s10, 120(sp); 
sw  s9,  116(sp);
sw  s8,  112(sp);
sw  s7,  108(sp);
sw  s6,  104(sp);
sw  s5,  100(sp);
sw  s4,   96(sp);
sw  s3,   92(sp);
sw  s2,   88(sp);
sw  s1,   84(sp);
sw  s0,   80(sp);
sw  ra,   76(sp);
mv  s0, a0
mv  s1, a1
mv  s2, a2
mv  s3, a3
----

include::Zces_footer.adoc[]

