<<<
[#insns-cm_jalt,reftext="cm.jalt: jump via table and link to ra"]
=== cm.jalt

Synopsis::
jump via table and link to ra

Mnemonic::
cm.jalt  _index_

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: ['C2'] },
    { bits:  8, name: 'index' , attr: [] },
    { bits:  3, name: 0x0,      attr: [] },
    { bits:  3, name: 0x5,      attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

  For this encoding to decode as _cm.jalt_, _index>=64_, otherwise it decodes as <<insns-cm_jt>>.

[NOTE]

  The equivalent encoding with bit[10]=1 is reserved to allow future expansion of the table index.

Assembly Syntax::

[source,sail]
--
cm.jalt index
--

Description::

_cm.jalt_ reads an entry from the jump vector table in memory and jumps to the address that was read, linking to _ra_.

For further information see <<insns-tablejump>>.

Prerequisites::
None

32-bit equivalent::
No direct equivalent encoding exists.

<<<

[#insns-cm_jalt-SAIL,reftext="cm.jalt SAIL code"]
Operation::

[source,sail]
--
//This is not SAIL, it's pseudo-code. The SAIL hasn't been written yet.

# target_address is temporary internal state, it doesn't represent a real register
# Mem is byte indexed

switch(XLEN) {
  32:  table_address[XLEN-1:0] = JVT.base + (index<<2);
  64:  table_address[XLEN-1:0] = JVT.base + (index<<3);
}

//fetch from the jump table
target_address[XLEN-1:0] = InstMemory[table_address][XLEN-1:0];

//jump to the target address
jalr ra, target_address[XLEN-1:0]&~0x1;

--



include::Zcmt_footer.adoc[]

