<<<
[#insns-cm_push,reftext="cm.push: Create stack frame: push registers, allocate additional stack space."]
=== cm.push

Synopsis::
Create stack frame: store ra and 0 to 12 saved registers to the stack frame, optionally allocate additional stack space.

Mnemonic::
cm.push

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: [] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x16,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

  _rlist_ values 0 to 3 are reserved for a future EABI variant called _cm.push.e_

Assembly Syntax::

[source,sail]
--
cm.push {reg_list},  -stack_adj
cm.push {xreg_list}, -stack_adj
--

include::variable_def.adoc[]
include::pushpop_vars.adoc[]

<<<
Description::
This instruction pushes (stores) the registers in _reg_list_ to the memory below the stack pointer, 
and then creates the stack frame by decrementing the stack pointer by _stack_adj_, 
including any additional stack space requested by the value of _spimm_.

include::pushpop_extra_info.adoc[]
include::cm_push_stores_pseudo_code.adoc[]
include::cm_push_pseudo_code.adoc[]

<<<

RV32I Assembly example::

[source,sail]
----
cm.push  {ra, s0-s2}, -64
----

Encoding: _rlist_=7, _spimm_=3

The equivalent interrupt-safe instruction sequence is:

[source,sail]
----
addi sp, sp, -64;
sw  s2, 60(sp);
sw  s1, 56(sp); 
sw  s0, 52(sp);
sw  ra, 48(sp); 
----

RV32I Assembly example::

[source,sail]
----
cm.push {ra, s0-s1}, -32
----

Encoding: _rlist_=6, _spimm_=1

The equivalent interrupt-safe instruction sequence is:

[source,sail]
----
addi sp, sp, -32;
sw  s1, 28(sp);
sw  s0, 24(sp); 
sw  ra, 20(sp);
----

RV32I Assembly example::

[source,sail]
----
cm.push  {ra, s0-s3}, -64
----

Encoding: _rlist_=8, _spimm_=2

The equivalent interrupt-safe instruction sequence is:

[source,sail]
----
addi sp, sp, -64;
sw  s3, 60(sp);
sw  s2, 56(sp); 
sw  s1, 52(sp);
sw  s0, 48(sp); 
sw  ra, 44(sp); 
----

<<<

RV32I Assembly example::

[source,sail]
----
cm.push {ra, s0-s11}, -112
----

Encoding: _rlist_=15, _spimm_=3

The equivalent interrupt-safe instruction sequence is:

[source,sail]
----
addi sp, sp, -112;
sw  s11, 108(sp);
sw  s10, 104(sp); 
sw  s9,  100(sp);
sw  s8,   96(sp);
sw  s7,   92(sp);
sw  s6,   88(sp);
sw  s5,   84(sp);
sw  s4,   80(sp);
sw  s3,   76(sp);
sw  s2,   72(sp);
sw  s1,   68(sp);
sw  s0,   64(sp);
sw  ra,   60(sp);
----

include::Zcmp_footer.adoc[]
include::Zcmpe_footer.adoc[]
