<<<
[#insns-cm_popret,reftext="cm.popret: Destroy stack frame: pop registers, deallocate stack frame, return."]
=== cm.popret

Synopsis::
Destroy stack frame: load ra and 0 to 12 saved registers from the stack frame, deallocate the stack frame, return to ra.

Mnemonic::
cm.popret _{reg_list}, stack_adj_

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: ['C2'] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x1e,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

  _rlist_ values 0 to 3 are reserved for a future EABI variant called _cm.popret.e_

Assembly Syntax::

[source,sail]
--
cm.popret {reg_list},  stack_adj
cm.popret {xreg_list}, stack_adj
--

include::variable_def.adoc[]
include::pushpop_vars.adoc[]

<<<

Description::
This instruction pops (loads) the registers in _reg_list_ from stack memory,
 adjusts the stack pointer by _stack_adj_ and then returns to _ra_.

include::pushpop_extra_info.adoc[]
include::cm_pop_popret_loads_pseudo_code.adoc[]
include::cm_popret_pseudo_code.adoc[]

<<<

RV32I Assembly example::

[source,sail]
--
cm.popret {ra}, 16
--

Encoding: _rlist_=4, _spimm_=0

The equivalent interrupt-safe instruction sequence is:

[source,sail]
--
lw   ra, 12(sp);
addi sp, sp, 16;
ret;
--

RV32I Assembly example::

[source,sail]
--
cm.popret {ra, s0-s2}, 48
--

Encoding: _rlist_=7, _spimm_=2

The equivalent interrupt-safe instruction sequence is:

[source,sail]
--
lw   s2, 44(sp);
lw   s1, 40(sp);  
lw   s0, 36(sp);  
lw   ra, 32(sp);  
addi sp, sp, 48;
ret;
--

RV32I Assembly example::

[source,sail]
--
cm.popret {ra, s0-s3}, 48
--

Encoding: _rlist_=8, _spimm_=1

The equivalent interrupt-safe instruction sequence is:

[source,sail]
--
lw   s3, 44(sp);
lw   s2, 40(sp);  
lw   s1, 36(sp);  
lw   s0, 32(sp);  
lw   ra, 28(sp);  
addi sp, sp, 48;
ret;
--

<<<

RV32I Assembly example::

[source,sail]
--
cm.popret {ra, s0-s4}, 64
--

Encoding: _rlist_=9, _spimm_=2

The equivalent interrupt-safe instruction sequence is:

[source,sail]
--
lw   s4, 60(sp);
lw   s3, 56(sp);
lw   s2, 52(sp);  
lw   s1, 48(sp);  
lw   s0, 44(sp);  
lw   ra, 40(sp);  
addi sp, sp, 64;
ret;
--

include::Zcmp_footer.adoc[]
include::Zcmpe_footer.adoc[]

