<<<

[#insns-pushpop,reftext="PUSH/POP Register Instructions"]
== PUSH/POP register instructions

These instructions are collectively referred to as PUSH/POP: 

* <<#insns-c_push>> 
* <<#insns-c_pop>> 
* <<#insns-c_popret>> 
* <<#insns-c_popretz>> 

The term PUSH refers to _c.push_.

The term POP refers to _c.pop_.

The term POPRET refers to _c.popret and c.popretz_.

Common details for these instructions are in this section.

=== PUSH/POP functional overview

PUSH, POP, POPRET are used to reduce the size of function prologues and epilogues.

. The PUSH instruction
** pushes (stores) the registers specified in the register list to the stack frame
** adjusts the stack pointer to create the stack frame

. The POP instruction
** pops (loads) the registers in the register list from the stack frame
** adjusts the stack pointer to destroy the stack frame

. The POPRET instructions
** pop (load) the registers in the register list from the stack from
** _c.popretz_ also moves zero into _a0_ as the return value
** adjust the stack pointer  to destroy the stack frame
** execute a _ret_ instruction to return from the function

<<<
=== Example usage

This example gives an illustration of the use of PUSH and POPRET.

The function _processMarkers_ in the EMBench benchmark picojpeg in the following file on github: https://github.com/embench/embench-iot/blob/master/src/picojpeg/libpicojpeg.c[libpicojpeg.c]

The prologue and epilogue compile with GCC10 to:

[source,SAIL]
----

   0001098a <processMarkers>:
   1098a:       711d                    addi    sp,sp,-96 ;#c.push(1)
   1098c:       c8ca                    sw      s2,80(sp) ;#c.push(2)
   1098e:       c6ce                    sw      s3,76(sp) ;#c.push(3)
   10990:       c4d2                    sw      s4,72(sp) ;#c.push(4)
   10992:       ce86                    sw      ra,92(sp) ;#c.push(5)
   10994:       cca2                    sw      s0,88(sp) ;#c.push(6)
   10996:       caa6                    sw      s1,84(sp) ;#c.push(7)
   10998:       c2d6                    sw      s5,68(sp) ;#c.push(8)
   1099a:       c0da                    sw      s6,64(sp) ;#c.push(9)
   1099c:       de5e                    sw      s7,60(sp) ;#c.push(10)
   1099e:       dc62                    sw      s8,56(sp) ;#c.push(11)
   109a0:       da66                    sw      s9,52(sp) ;#c.push(12)
   109a2:       d86a                    sw      s10,48(sp);#c.push(13)
   109a4:       d66e                    sw      s11,44(sp);#c.push(14)
...
   109f4:       4501                    li      a0,0      ;#c.popretz(1)
   109f6:       40f6                    lw      ra,92(sp) ;#c.popretz(2)
   109f8:       4466                    lw      s0,88(sp) ;#c.popretz(3)
   109fa:       44d6                    lw      s1,84(sp) ;#c.popretz(4)
   109fc:       4946                    lw      s2,80(sp) ;#c.popretz(5)
   109fe:       49b6                    lw      s3,76(sp) ;#c.popretz(6)
   10a00:       4a26                    lw      s4,72(sp) ;#c.popretz(7)
   10a02:       4a96                    lw      s5,68(sp) ;#c.popretz(8)
   10a04:       4b06                    lw      s6,64(sp) ;#c.popretz(9)
   10a06:       5bf2                    lw      s7,60(sp) ;#c.popretz(10)
   10a08:       5c62                    lw      s8,56(sp) ;#c.popretz(11)
   10a0a:       5cd2                    lw      s9,52(sp) ;#c.popretz(12)
   10a0c:       5d42                    lw      s10,48(sp);#c.popretz(13)
   10a0e:       5db2                    lw      s11,44(sp);#c.popretz(14)
   10a10:       6125                    addi    sp,sp,96  ;#c.popretz(15)
   10a12:       8082                    ret               ;#c.popretz(16)
----

<<<

with the GCC option _-msave-restore_ the output is the following:

[source,SAIL]
----
0001080e <processMarkers>:
   1080e:       73a012ef                jal     t0,11f48 <__riscv_save_12>
   10812:       1101                    addi    sp,sp,-32
...
   10862:       4501                    li      a0,0
   10864:       6105                    addi    sp,sp,32
   10866:       71e0106f                j       11f84 <__riscv_restore_12>
----

with PUSH/POPRET this reduces to

[source,SAIL]
----
0001080e <processMarkers>:
   1080e:       xxxx                    c.push    {ra,s0-s11},-96
...
   10866:       xxxx                    c.popretz {ra,s0-s11}, 96
----

The prologue / epilogue reduce from 58-bytes in the original code, to 16-bytes with _-msave-restore_, 
and to 6-bytes with PUSH and POPRET. 
As well as reducing the code-size PUSH and POPRET eliminate the branches from 
calling the millicode _save/restore_ routines and so also perform better. 
  
[NOTE]

  The calls to _<riscv_save_0>/<riscv_restore_0>_ become 64-bit when the target functions are out of the ±1MB range, increasing the prologue/epilogue size to 22-bytes.

[NOTE]

  POP is typically used in tail-calling sequences where _ret_ is not used to return to _ra_ after destroying the stack frame.

[#pushpop-areg-list]

=== Compiler implementation

The technique used in the initial implementation in LLVM is to let the compiler generate the function prologue and epilogue, 
and then replace the instruction sequences with the relevant PUSH/POP instructions.

==== _spimm_ handling

The instructions have a restricted range of _spimm_ available. If this is insufficient then a separate _c.addi16sp_ can be used to increase the range.

==== register list handling

The instructions do not directly support _{ra, s0-s10}_ to reduce the amount of encoding space required. If this register list is required then _s11_ 
should also be included. This costs a small amount of memory and performance, but saves code-size.

<<<

[#pushpop-fault-handling]
=== PUSH/POP Fault handling

The sequence required to execute the PUSH/POP instruction may be interrupted, or may not be able to start execution for several reasons.

* virtual memory page fault or PMP fault
** these can be detected before execution, or during execution if the memory addresses cross a page/PMP boundary
** xTVAL is set to any address which causes the fault
* watchpoint trigger
** these can be detected before execution, or during execution depending on the trigger type (load data triggers require the sequence to have started executing, for example)
** xTVAL is set to any address which causes the fault
* external debug halt
** the halt can treat the whole sequence atomically, or interrupt mid sequence (implementation defined)
* debug halt caused by a trigger
** same comment as watchpoint trigger above
* load access fault
** these are detected while the sequence is executing
** xTVAL is set to the fault address.
* store access fault (precise or imprecise)
** these may be detected while the sequence is executing, or afterwards if imprecise
** xTVAL is set to the fault address.
* interrupts
** these may arrive at any time. An implementation can choose whether to interrupt the sequence or not.

[NOTE]

  xTVAL may be hardwired to zero in an implementation. Recovering from faults such as page faults requires that it is implemented.

In all cases MEPC contains the PC of the PUSH/POP instruction, and MCAUSE is set as expected for the type of fault.

For debug halts DPC is set to the PC of the PUSH/POP instruction.

Because some faults can only be detected during the sequence the core implementation must be able to recover from the fault and re-execute the sequence. 
This may involve executing some or all of the loads and stores from the sequence multiple times before the sequence completes (as multiple faults or multiple interrupts are possible).

Therefore correct execution requires that _sp_ refers to idempotent memory (also see <<pushpop_non-idem-mem>>).

<<<

[#pushpop-software-view]
=== Software view of execution

==== Software view of the PUSH sequence

From a software perspective the PUSH sequence appears as:

* A sequence of stores writing a contiguous block of memory. Any of the bytes may be written multiple times.
* A stack pointer adjustment

Because the memory is idempotent and the stores are non-overlapping, they may be reordered, grouped into larger accesses, split into smaller access or any combination of these.

If an implementation allows interrupts during the sequence, and the interrupt handler uses _sp_ to allocate stack memory, then any stores which were executed before the interrupt may be overwritten by the handler. 
This is safe because the memory is idempotent and the stores will be re-executed when execution resumes.

The stack pointer adjustment must only be committed once it is certain that all of the stores will complete without triggerring any precise faults (for example, page faults). 
Stores may also return imprecise faults from the bus. It is platform defined whether the core implementation waits for the bus responses before continuing to the final stage of the sequence, 
or handles errors responses after completing the PUSH instruction.

<<<

For example:

[source,sail]
--
c.push  {ra, s0-s5}, -64
--

Appears to software as:

[source,sail]
--
# any bytes from sp-1 to sp-28 may be written multiple times before the instruction completes
# therefore these updates may be visible in the interrupt/exception handler below the stack pointer
sw  s5, -4(sp)   
sw  s4, -8(sp)   
sw  s3,-12(sp)   
sw  s2,-16(sp)  
sw  s1,-20(sp)   
sw  s0,-24(sp)   
sw  ra,-28(sp)   

# this must only execute once, and will only execute after all stores completed without any precise faults
# therefore this update is only visible in the interrupt/exception handler if c.push has completed
addi sp, sp, -64
--

==== Software view of the POP/POPRET sequence

From a software perspective the POP/POPRET sequence appears as:

* A sequence of loads, any of which may be executed multiple times
* A stack pointer adjustment
* An optional LI zero into a0
* An optional RET

If an implementation allows interrupts during the sequence, then any loads which were executed before the interrupt may update architectural state. 
The loads will be re-executed once the handler completes, so the values will be overwritten. 
Therefore it is permitted for an implementation to update some of the destination registers before taking the interrupt or other fault.

The optional load immediate and stack pointer adjustment must only be committed once it is certain that all of the loads will complete successfully.

For POPRET once the stack pointer adjustment has been committed the RET must execute.

<<<
For example:

[source,sail]
--
c.popretz {ra, s0-s3}, 32; 
--

Appears to software as:

[source,sail]
--
# any or all of these load instructions may execute multiple times
# therefore these updates may be visible in the interrupt/exception handler
lw   s3, 28(sp)
lw   s2, 24(sp)
lw   s1, 20(sp)
lw   s0, 16(sp)
lw   ra, 12(sp)

# these must only execute once, will only execute after all loads complete successfully
# all instructions must execute atomically
# therefore these updates are not visible in the interrupt/exception handler
li a0, 0
addi sp, sp, 32
ret
--

=== Forward progress guarantee

The PUSH/POP sequence has the same forward progress guarantee as executing the instructions from the equivalent assembly sequences.

[[pushpop_non-idem-mem]]
=== Non-idempotent memory handling

An implementation may have a requirement to issue a PUSH/POP instruction to non-idempotent memory. 

==== Error detection

If the core implementation does not support PUSH/POP to non-idempotent memories, the core may use an idempotency PMA to detect it and take a 
load(POP/POPRET) or store (PUSH) access fault exception in order to avoid unpredictable results.

<<<

==== Non-idempotent support

It is possible to support non-idempotent memory. One reason is to re-use PUSH/POP as a restricted form of a load/store multiple instruction to a peripheral,
as there is no generic load/store multiple instruction in the RISC-V ISA. 

If accessing non-idempotent memory then it is _recommended_ to:

. Not allow interrupts during execution
. Not allow external debug halt during execution
. Detect any virtual memory page faults or PMP faults for the whole instruction before starting execution (instead of during the sequence)
. Not split / merge / reorder the generated memory accesses

It is possible that one of the following will still occur during execution:

. Watchpoint trigger
. Load/store access fault

In these cases the core will jump to the debug or exception handler. If execution is required to continue afterwards (so the event is not fatal to the code execution), then the handler is required to do so in software. 

By following these rules memory accesses will only ever be issued once, and decreasing address order.

It is possible for implementations to follow these restricted rules and to safely access both types of memory. 
It is also possible for an implementation to use PMAs to detect the memory type and apply different rules, such as only allowing interrupts if accessing cacheable memory, for example.

include::Zcyp_footer.adoc[]
