<<<

[#insns-tablejump,reftext="Table Jump Instructions"]
== Table Jump Instructions

These instructions are collectively referred to as table jump: 

* <<#insns-c_jt>> 
* <<#insns-c_jalt>> 

Common details for these instructions are in this section.

=== Table Jump Overview

Table jump is a form of dictionary compression used to reduce the code size of JAL / AUIPC+JALR / JR / AUIPC+JR instructions.

Function calls and jumps to fixed labels typically take 32-bit or 64-bit instruction sequences.

Table jump allows the linker to:

* replace 32-bit _j_ calls with _c.jt_
* replace 32-bit _jal_ ra calls with _c.jalt_
* replace 64-bit _auipc/jalr_ calls to fixed locations with _c.jt_
* replace 64-bit _auipc/jalr ra_ calls to fixed locations with _c.jalt_
** The AUIPC+JR/JALR sequence is used because the offset from the PC is out of the ±1MB range.

=== JVT

The base of the table is in the JVT CSR (see <<csrs-jvt>>), each table entry is XLEN bits.

The table entry number is from the _index8_ field in the encoding, which controls the link register.

* c.jt   : entries 0-63,   link to _zero_
* c.jalt : entries 64-255, link to _ra_

Note that the LSB of every jump table entry is _ignored_ which matches standard JALR behaviour.

If the same function is called with and without linking then it must have two entries in the table. 
This case does happen in practice but only affects a small number of entries so it does not waste much space in the table. 
It is typically caused by the same function being called with and without tail calling.

<<<
[#tablejump-algorithm]
=== Recommended algorithm for allocating entries in the jump table

Calls to each function are categorised as shown in <<tablejump-savings>>.

[#tablejump-savings]
.Table jump code size saving for each function call replacement
[width="100%",options=header]
|=======================================================================================================================
| original sequence | Table Jump saving  
| J                 | A*2-(XLEN/8) bytes 
| AUIPC+JR          | B*6-(XLEN/8) bytes 
| JAL ra            | C*2-(XLEN/8) bytes 
| AUIPC+JALR ra     | D*6-(XLEN/8) bytes 
|=======================================================================================================================

Each function is called by using one of the two link registers. The total saving per function is calculated by counting the number of calls and adding up the total saving from each replacement of the existing sequence with a Table Jump instruction, as follows:
[source,sourceCode,text]
----
saving_per_function_c_jt    = A * 2 + B * 6 - 2*(XLEN-8)
saving_per_function_c_jalt  = C * 2 + D * 6 - 2*(XLEN-8)
----

The functions are sorted so that the one with the highest saving is in table entry 0, the second highest in entry 1 etc. for that encoding.

[NOTE]

  This algorithm assumes that each function is only called with one link register. 
  If the same function is called with more than one link register, then it must have two entries in the table.

This allows the core to cache the most frequent targets by caching the lowest numbered entries of each section of the jump table. 
Only caching a few entries will greatly improve the performance.

<<<
[#tablejump-fault-handling]
=== Table Jump Fault handling

Table Jump involves two instruction fetches from a single instruction, and either fetch can cause a fault. There are no data accesses involved in the execution of table jumps.

The sequence required to execute the table jump instruction may be interrupted, or may not be able to start execution for several reasons.

* virtual memory page fault or PMP fault
** these can be detected before execution, or during execution if the table jump instruction and the address in the table map to different virtual memory pages or PMP regions
* watchpoint trigger or debug halt caused by a trigger
* external debug halt
** the halt can treat the whole sequence atomically, or interrupt mid sequence (implementation defined)
* interrupts
** these may arrive at any time. An implementation can choose whether to interrupt the sequence or not.

For exceptions and interrupts MEPC contain the PC of the table jump instruction, MCAUSE is set as expected for the type of fault and MTVAL contains the address which caused the fault.

For debug halts DPC is set to the PC of the table jump instruction.

This section gives an overview of the behaviour, the exact operation is documented in the SAIL code for each instruction: <<insn-c_jalt-SAIL>>, <<insn-c_jt-SAIL>>.

include::Zcyp_footer.adoc[]
