==== Zcee

Zcee is the first subset of the code-size reduction extension Zce to be proposed for public review. The instructions are all very simple and are 16-bit encodings of existing instructions, either from the I/E ISA or from Zbb.

All proposed encodings are currently reserved for all architectures, and have no conflicts with any existing extensions.

All of the sign and zero extension instructions use the same format. These typically benefit code-size because if the compiler is working with fewer than XLEN bits it must size/zero extend the value to XLEN bits before calling a function, or passing a return value.

c.sext.\*, c.zext.* encoding group::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0, attr: ['OP=C0'] },
    { bits:  3, name: 'opcode' },
    { bits:  2, name: 0x0, attr: ['FUNCT2'] },
    { bits:  3, name: 'rsd\'', attr: ['SRCDST'] },
    { bits:  6, name: 0x20, attr: ['FUNCT6'] },
],config:{bits:16}}
....

The c.mul encoding has the register sources/destination in the same fields as other 16-bit encodings such as c.sub, c.xor etc. c.mul has a high benefit for audio processing algorithms and for a variety of other benchmarks.

c.mul encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['OP=C1'] },
    { bits:  3, name: 'rs2\'', attr: ['SRC2']  },
    { bits:  2, name: 0x2, attr: ['FUNCT2'] },
    { bits:  3, name: 'rsd\'', attr: ['SRCDST'] },
    { bits:  6, name: 0x27, attr: ['FUNCT6'] },
],config:{bits:16}}
....

Benchmark results are in https://docs.google.com/spreadsheets/d/1UYll7HGR_QLGTsHcjGoNL4EodM5BNO41hXdxVAFaxFs/edit#gid=1281210325[this spreadsheet].

[NOTE]

  `c.sext.w` will be a pseudo-instruction for `c.addiw rd, 0` (RV64/RV128)

[%header,cols="^1,^1,^1,4,8"]
|===
|RV 32
|RV 64
|RV 128
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|&#10003;
|c.sext.b _rsd'_
|<<#insns-c_sext_b>> 

|&#10003;
|&#10003;
|&#10003;
|c.sext.h _rsd'_
|<<#insns-c_sext_h>> 

|&#10003;
|&#10003;
|&#10003;
|c.zext.b _rsd'_
|<<#insns-c_zext_b>> 

|&#10003;
|&#10003;
|&#10003;
|c.zext.h _rsd'_
|<<#insns-c_zext_h>> 

|
|&#10003;
|&#10003;
|c.zext.w _rsd'_
|<<#insns-c_zext_w>> 

|&#10003;
|&#10003;
|&#10003;
|c.mul _rsd'_, _rs2'_
|<<#insns-c_mul>> 

|===

include::c_sext_b.adoc[]
include::c_sext_h.adoc[]
include::c_zext_b.adoc[]
include::c_zext_h.adoc[]
include::c_zext_w.adoc[]
include::c_mul.adoc[]

