[#Zcee]
==== Zcee 0.53.1

This document is in the Stable state. Assume anything could still change, but limited change should be expected. For more information see:
https://riscv.org/spec-state

The instructions in Zcee are all very simple and are 16-bit encodings of existing instructions, either from the I/E ISA or from Zbb.

All proposed encodings are currently reserved for all architectures, and have no conflicts with any existing extensions.

All of the sign and zero extension instructions use the same format.
These typically benefit code-size because if the compiler is working with fewer than XLEN bits it must sign/zero extend the value to XLEN bits before calling a function, or passing a return value.

Encoding (RV32, RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['OP=C1'] },
    { bits:  3, name: 'opcode' },
    { bits:  2, name: 0x0, attr: ['FUNCT2'] },
    { bits:  3, name: 'rsd\'', attr: ['SRCDST'] },
    { bits:  6, name: 0x23, attr: ['FUNCT6'] },
],config:{bits:16}}
....

The _c.mul_ encoding uses the CR register format along with other instructions such as _c.sub_, _c.xor_ etc. 

[NOTE]

  _c.sext.w_ is a pseudo-instruction for _c.addiw rd, 0_ (RV64)

[%header,cols="^1,^1,4,8"]
|===
|RV 32
|RV 64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|c.sext.b _rsd'_
|<<#insns-c_sext_b>> 

|&#10003;
|&#10003;
|c.sext.h _rsd'_
|<<#insns-c_sext_h>> 

|&#10003;
|&#10003;
|c.zext.b _rsd'_
|<<#insns-c_zext_b>> 

|&#10003;
|&#10003;
|c.zext.h _rsd'_
|<<#insns-c_zext_h>> 

|
|&#10003;
|c.zext.w _rsd'_
|<<#insns-c_zext_w>> 

|&#10003;
|&#10003;
|c.mul _rsd'_, _rs2'_
|<<#insns-c_mul>> 

|===

include::c_sext_b.adoc[]
include::c_sext_h.adoc[]
include::c_zext_b.adoc[]
include::c_zext_h.adoc[]
include::c_zext_w.adoc[]
include::c_mul.adoc[]

