[#Zces]
==== Zces 0.53.4

This document is in the Stable state. Assume anything could still change, but limited change should be expected. For more information see:
https://riscv.org/spec-state

Zces is the set of sequenced or more complex instuctions for code-size reduction.

This extension reuses encodings from the D-extension.  Therefore it is _incompatible_ with D. It is fully compatible with F and also with Zdinx.

[NOTE]

  jt and jalt require <<#csrs-jvt>>.

[NOTE]

  The PUSH/POP instructions share assembly mnemonics for different encodings. For further information see <<insns-pushpop>>.

The PUSH/POP assembly syntax uses several variables, the meaning of which are:

* _reg_list_ is a list containing 1 to 13 registers (ra and 0 to 12 s registers)
** valid values: {ra}, {ra, s0}, {ra, s0-s1}, {ra, s0-s2}, ..., {ra, s0-s8}, {ra, s0-s9}, {ra, s0-s11}
** note that {ra, s0-s10} is _not_ valid, giving 12 lists not 13 for better encoding
* _areg_list_ is a list containing 1 to 3 a registers
** valid values: {a0}, {a0-a1}, {a0-a2}
* _stack_adj_ is the total size of the stack frame. 
** valid values vary with register list length and the specific encoding, see the instruction pages for details.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|c.push {reg_list}, -stack_adj
|<<#insns-c_push>> 

|&#10003;
|&#10003;
|c.push {reg_list}, {areg_list}, -stack_adj
|<<#insns-c_pusha>> 

|&#10003;
|&#10003;
|c.pop {reg_list}, stack_adj
|<<#insns-c_pop>> 

|&#10003;
|&#10003;
|c.popret {reg_list}, stack_adj
|<<#insns-c_popret>> 

|&#10003;
|&#10003;
|c.popretz {reg_list}, stack_adj
|<<#insns-c_popretz>> 

|&#10003;
|&#10003;
|c.jt #index
|<<#insns-c_jt>> 

|&#10003;
|&#10003;
|c.jalt #index
|<<#insns-c_jalt>> 

|&#10003;
|&#10003;
|c.mva01s sreg1, sreg2
|<<#insns-c_mva01s>> 

|===

include::c_push.adoc[]
include::c_pusha.adoc[]
include::c_pop.adoc[]
include::c_popret.adoc[]
include::c_popretz.adoc[]
include::c_jt.adoc[]
include::c_jalt.adoc[]
include::JVT_csr.adoc[]
include::c_mva01s.adoc[]
include::pushpop.adoc[]
include::tablejump.adoc[]

